"""Internal helper called by setup.sh — never invoke directly.

Prompts for a username + password, generates a bcrypt hash and a JWT secret,
and writes a fresh .env with mode 0600. Doing this entirely in Python sidesteps
the classic shell-mangling bug where $2b / $12 / $1 in a bcrypt hash get eaten
as positional parameters.
"""

import getpass
import os
import secrets
import sys

import bcrypt

ENV_PATH = ".env"


def main() -> int:
    if os.path.exists(ENV_PATH):
        print(f"{ENV_PATH} already exists; refusing to overwrite.", file=sys.stderr)
        print("Delete it manually if you really want to regenerate.", file=sys.stderr)
        return 1

    default_user = os.environ.get("USER") or "mayeul"
    username = input(f"Username [{default_user}]: ").strip() or default_user

    while True:
        pw = getpass.getpass("Password: ")
        if not pw:
            print("Empty password, aborting.", file=sys.stderr)
            return 1
        if len(pw.encode("utf-8")) > 72:
            print("bcrypt limit: password must be ≤72 bytes — try a shorter one.")
            continue
        confirm = getpass.getpass("Confirm:  ")
        if pw == confirm:
            break
        print("Mismatch, try again.")

    hash_ = bcrypt.hashpw(pw.encode("utf-8"), bcrypt.gensalt()).decode("utf-8")
    jwt_secret = secrets.token_urlsafe(64)

    contents = f"""\
# Generated by scripts/setup.sh — edit by hand if you need to change values.
# Never commit this file. Mode is 0600 so only your user can read it.

OMILOG_USERNAME={username}
OMILOG_PASSWORD_HASH={hash_}
OMILOG_JWT_SECRET={jwt_secret}
OMILOG_JWT_ALGORITHM=HS256
OMILOG_JWT_EXPIRE_MINUTES=10080

OMILOG_STORAGE_DIR=storage
OMILOG_DB_PATH=omilog.db

OMILOG_HOST=127.0.0.1
OMILOG_PORT=8000
OMILOG_LOG_LEVEL=INFO
"""
    with open(ENV_PATH, "w", encoding="utf-8") as f:
        f.write(contents)
    os.chmod(ENV_PATH, 0o600)
    print(f"Wrote {ENV_PATH} (mode 0600).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
